#Rails.application.secrets.secret_key_git_auth
development:
  secret_key_git_auth:
    111fb88663c18595261002019957e1d827e318f0
test:
  secret_key_git_auth:
    111fb88663c18595261002019957e1d827e318f0
production:
  secret_key_git_auth: <%= ENV["SECRET_KEY_GIT"] %>>